import { ResumeData } from './reactPdfTemplates'

/**
 * Parse HTML resume content into structured ResumeData
 * This extracts data from the HTML generated by OpenAI
 */
export function parseResumeHtml(html: string): ResumeData {
  // Create a temporary DOM element to parse the HTML
  const parser = new DOMParser()
  const doc = parser.parseFromString(html, 'text/html')
  const container = doc.querySelector('.resume-container')

  if (!container) {
    throw new Error('Invalid resume HTML: missing .resume-container')
  }

  // Extract name
  const nameElement = container.querySelector('.name')
  const name = nameElement?.textContent?.trim() || 'Unknown'

  // Extract contact info
  const contactInfoElement = container.querySelector('.contact-info')
  const contactInfoText = contactInfoElement?.textContent?.trim() || ''
  const contactInfo = contactInfoText
    .split('|')
    .map(item => item.trim())
    .filter(item => item.length > 0)

  // Extract summary
  const summarySection = findSectionByTitle(container, 'Summary')
  const summaryContent = summarySection?.querySelector('.section-content')
  const summary = summaryContent?.textContent?.trim() || ''

  // Extract experience
  const experienceSection = findSectionByTitle(container, 'Work Experience') || 
                            findSectionByTitle(container, 'Experience')
  const experience = extractJobEntries(experienceSection)

  // Extract portfolio (optional)
  const portfolioSection = findSectionByTitle(container, 'Portfolio') ||
                           findSectionByTitle(container, 'Projects')
  const portfolio = extractPortfolioEntries(portfolioSection)

  // Extract skills
  const skillsSection = findSectionByTitle(container, 'Skills') ||
                        findSectionByTitle(container, 'Technical Skills')
  const skills = extractSkills(skillsSection)

  // Extract education
  const educationSection = findSectionByTitle(container, 'Education')
  const education = extractEducationEntries(educationSection)

  return {
    name,
    contactInfo,
    summary,
    experience,
    portfolio: portfolio.length > 0 ? portfolio : undefined,
    skills,
    education,
  }
}

/**
 * Find a section by its title text
 */
function findSectionByTitle(container: Element, titleText: string): Element | null {
  const sections = container.querySelectorAll('.resume-section')
  
  for (const section of sections) {
    const title = section.querySelector('.section-title')
    if (title && title.textContent?.toLowerCase().includes(titleText.toLowerCase())) {
      return section
    }
  }
  
  return null
}

/**
 * Extract job entries from experience section
 */
function extractJobEntries(section: Element | null): Array<{ title: string; description: string }> {
  if (!section) return []
  
  const entries: Array<{ title: string; description: string }> = []
  const jobEntries = section.querySelectorAll('.job-entry')
  
  if (jobEntries.length > 0) {
    jobEntries.forEach(entry => {
      const titleElement = entry.querySelector('.job-title')
      const title = titleElement?.textContent?.trim() || ''
      
      // Get all text content except the title
      const description = Array.from(entry.querySelectorAll('p'))
        .map(p => p.textContent?.trim())
        .filter(Boolean)
        .join(' ')
      
      if (title) {
        entries.push({ title, description })
      }
    })
  } else {
    // Fallback: try to extract from section content directly
    const content = section.querySelector('.section-content')
    if (content) {
      const text = content.textContent?.trim() || ''
      if (text) {
        entries.push({ title: 'Experience', description: text })
      }
    }
  }
  
  return entries
}

/**
 * Extract portfolio/project entries
 */
function extractPortfolioEntries(section: Element | null): Array<{ title: string; description: string; links?: string }> {
  if (!section) return []
  
  const entries: Array<{ title: string; description: string; links?: string }> = []
  const portfolioEntries = section.querySelectorAll('.portfolio-entry')
  
  if (portfolioEntries.length > 0) {
    portfolioEntries.forEach(entry => {
      const titleElement = entry.querySelector('.project-title')
      const title = titleElement?.textContent?.trim() || ''
      
      const description = Array.from(entry.querySelectorAll('p:not(.project-links)'))
        .map(p => p.textContent?.trim())
        .filter(Boolean)
        .join(' ')
      
      const linksElement = entry.querySelector('.project-links')
      const links = linksElement?.textContent?.trim()
      
      if (title) {
        entries.push({ title, description, links })
      }
    })
  } else {
    // Try job-entry class (some templates might use it for projects)
    const jobEntries = section.querySelectorAll('.job-entry')
    jobEntries.forEach(entry => {
      const titleElement = entry.querySelector('.job-title') || entry.querySelector('h3')
      const title = titleElement?.textContent?.trim() || ''
      
      const description = Array.from(entry.querySelectorAll('p'))
        .map(p => p.textContent?.trim())
        .filter(Boolean)
        .join(' ')
      
      if (title) {
        entries.push({ title, description })
      }
    })
  }
  
  return entries
}

/**
 * Extract skills from skills section
 */
function extractSkills(section: Element | null): string[] {
  if (!section) return []
  
  const skillsList = section.querySelector('.skills-list')
  
  if (skillsList) {
    const items = skillsList.querySelectorAll('li')
    return Array.from(items)
      .map(item => item.textContent?.trim() || '')
      .filter(skill => skill.length > 0)
  }
  
  // Fallback: try to extract from text content
  const content = section.querySelector('.section-content')
  if (content) {
    const text = content.textContent?.trim() || ''
    // Split by common delimiters
    return text
      .split(/[,|•·]/)
      .map(skill => skill.trim())
      .filter(skill => skill.length > 0 && skill.length < 50)
  }
  
  return []
}

/**
 * Extract education entries
 */
function extractEducationEntries(section: Element | null): Array<{ degree: string; school: string; details?: string }> {
  if (!section) return []
  
  const entries: Array<{ degree: string; school: string; details?: string }> = []
  const educationEntries = section.querySelectorAll('.education-entry')
  
  if (educationEntries.length > 0) {
    educationEntries.forEach(entry => {
      const degreeElement = entry.querySelector('.degree-title')
      const schoolElement = entry.querySelector('.school-info')
      
      const degree = degreeElement?.textContent?.trim() || ''
      const school = schoolElement?.textContent?.trim() || ''
      
      // Get additional details (paragraphs that aren't school-info)
      const details = Array.from(entry.querySelectorAll('p:not(.school-info)'))
        .map(p => p.textContent?.trim())
        .filter(Boolean)
        .join(' ')
      
      if (degree || school) {
        entries.push({ degree, school, details: details || undefined })
      }
    })
  } else {
    // Fallback: try to extract from section content
    const content = section.querySelector('.section-content')
    if (content) {
      const text = content.textContent?.trim() || ''
      if (text) {
        entries.push({ degree: text, school: '' })
      }
    }
  }
  
  return entries
}
